<?php 
/* @var $block \DentalSpeed\ProdutoParcelamento\Block\Product\View\Parcelamento */

$numeroParcelas = $block->getProdutoAtributoPersolalizado('num_parcelas');
$valorParcelado = $block->getProdutoValorParcelado();
$valorParceladoLista = $block->getProdutoValorParceladoLista();

/* $_product = $block->getLayout()->createBlock('Catalog\Product\Block\ProductInfo')->getCurrentProduct();

var_dump($_product); */


if($numeroParcelas > 1){ ?>
<div class="product-info-parcelamento">
    <?php echo "ou em ".$numeroParcelas."x de ".$valorParcelado." sem juros"; ?>
</div>
<?php
}

echo "|------|";